### ISSUE TITLE
Switching brightness with shoulder buttons

### ISSUE THREAD

**Issue by fgl82** [retrofw/retrofw.github.io#15]
Description: the right shoulder button increases brightness but the left shoulder button doesn't lower it.

FW Version: 2B
Screen: replacement "sony" screen

Steps to reproduce:

1) While in GMenu, press the brightness button
2) Once the brightness bar shows up, press the right shoulder button. Brightness will go up.
3) Press the left shoulder button
4) Brightness stays the same

**Comment by pingflood** [comment]
Good catch.

In earlier GMenuNX versions the popup slider worked only while holding Select button. And this behavior was clashing volume and brightness actions. That's why Select + L would only trigger volume control and Select + R would trigger backlight control.

In current version the Select + L/R will popup the slider and it will remain on screen for volume/backlight control. So now it is possible to implement the behavior you are expecting.

Working on that for upcoming versions.

**Comment by fgl82** [comment]
Thanks for the explanation.

**Comment by pingflood** [comment]
Fixed in the v2.1 release!

**Comment by fgl82** [comment]
Cool!
